@DDDSample_HostAddress = http://localhost:5241

GET {{DDDSample_HostAddress}}/api/Members/
Accept: application/json
X-API-Key: abc12345

###

GET {{DDDSample_HostAddress}}/api/orders/
Accept: application/json
X-API-Key: abc12345

###

GET {{DDDSample_HostAddress}}/api/products/
Accept: application/json
X-API-Key: abc12345